### ISSUE TITLE
Point docker-backup directly at data container

### ISSUE THREAD

**Issue by cmrn** [5pi/docker-backup#13]
It would make sense to me if I were able to tell `docker-backup` the name of the data container I want to back up, rather than the name of the container which is using the data container I want to back up.

One use case could be if the user has a single canonical data container, but many ephemeral or automatically created app containers.

To clarify with an example, borrowing from `README.md`:

----

Let say you have a container named `mysql-data` to keep `/var/lib/mysql`. You start up your mysql server by running:

    $ docker run --volumes-from=mysql-data --name mysql-server ...
Backup that data container:

<pre>
    $ docker-backup store mysql-data-backup.tar mysql-<b>data</b>
</pre>

**Comment by boombatower** [comment]
Due to this issue, #11, and lack of restore functionality on [s3 part of tool](https://github.com/docker-infra/docker-lloyd) I decided to create https://github.com/boombatower/docker-backup which operates on a simpler principle, but loses the ability to automatically create the data container before restoring data (ie if container exists it can restore data into it). Also works with Docker 1.3.x and has s3 restore option.

**Comment by discordianfish** [comment]
@cmrn The design idea was that you don't need to care about which and how many data volume containers a stateful container uses, you just need to point it to that container.
That being said, I understand how this can be confusing and I'm open to PRs etc to introduce a way to specify the data container directly.

**Comment by discordianfish** [comment]
Thanks to @akihiro, this is implemented.
