### ISSUE TITLE
rename of commands

### ISSUE THREAD

**Issue by TomNussbaumer** [5pi/docker-backup#17]
Maybe its just me, but naming the commands 'store' and 'restore' sounds like it is only seconds away from disaster.

Would you mind to rename them to 'load' and 'save'?

**Comment by discordianfish** [comment]
I don't see why load and save is better. It stores a volume container to disk and restores it on another system. 'load' and 'save' can also be easily confused with 'docker load' and 'docke save' which is storing the container state instead of their volumes. Last but not least, changing the commands now would break existing users, I don't think it's worth it. Hope you understand.
